package io.github.hck5722.ytmprobe

public class ProbeResult(
    public val darwinHttpOk: Boolean = false,
    public val darwinStatus: Int = 0,
    public val browseOk: Boolean = false,
    public val browseStatus: Int = 0,
    public val browseBytes: Int = 0,
    public val searchOk: Boolean = false,
    public val searchStatus: Int = 0,
    public val searchBytes: Int = 0,
    public val streamOk: Boolean = false,
    public val streamAttempts: Int = 0,
    public val streamFailure: String? = null,
    public val audioUrl: String? = null,
    public val audioHeaders: Map<String, String> = emptyMap(),
    public val audioMimeType: String? = null,
    public val audioItag: Int = -1,
    public val audioClient: String? = null,
    public val audioProfile: String? = null,
    public val isSabr: Boolean = false,
    public val streamDiagnostics: String = "not_run",
    public val streamRunSummaries: List<String> = emptyList(),
    public val sampleCandidates: Int = 0,
    public val samplePassed: Int = 0,
    public val sampleTrackResults: List<String> = emptyList(),
    public val streamBytesPulled: Long = 0,
    public val streamUrlObtained: Boolean = false,
    public val audioChunks: List<ByteArray> = emptyList(),
    public val audioExpectedBytes: Long? = null,
    public val audioComplete: Boolean = false,
    public val audioCachePath: String? = null,
    public val loginState: String = "SKIP_NO_CREDENTIAL",
    public val loginStatus: Int = 0,
    public val loginBytes: Int = 0,
    public val diagnostic: String = "",
    public val failureStage: String? = null,
    public val failureType: String? = null,
    public val failureMessage: String? = null,
)
